apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: frontend
        env:
        - name: frontend_DB_HOST
          value: frontend-mysql
        - name: frontend_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: frontend
        volumeMounts:
        - name: frontend-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: frontend-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
    tier: frontend
  type: LoadBalancer